version: '3'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    container_name: mssql-container
    ports:
      - "1433:1433"
      - "1434:1434"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DThesis2021
